version: "3"

x-aws-vpc: "vpc-087c858ec62a50f81"

services:
  api:
    build: .
    image: 677889882207.dkr.ecr.ap-northeast-1.amazonaws.com/hod-aiz-repository
    ports:
      - 8080:80
    deploy:
      replicas: 2
  mongo:
    image: mongo
    expose:
      - 27017
